### ISSUE TITLE
一个页面中同时有两个轮播图，会冲突，只能有一个生效

### ISSUE THREAD

**Issue by leimingming1996** [ParadeTo/page-switch#2]

**Comment by ParadeTo** [comment]
看看你的代码

**Comment by leimingming1996** [comment]
<ul class="film_focus_imgs">
			<li class="li">
			<div id="container" style="width: 1000px;height: 635px; overflow: hidden; margin: 0 auto; margin-bottom: 20px; border: solid 1px #red;">
		         <div class="sections">
			           <div class="section" id="section0">
								<ul>
								    <li class="cutomerli" style="opacity: 1;">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/9.jpg" style=""/>
										<a href="about-detail.jsp" style="color:red"><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/1.jpg" "/>
										<a ><p>案例详情</p></a>
									</li>	
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/2.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/3.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/4.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/5.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/6.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/7.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/8.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>														
								</ul>
					   </div>
					    <div class="section" id="section1">
								<ul>
								    <li class="cutomerli" style="opacity: 1;">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/10.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/11.jpg" "/>
										<a ><p>案例详情</p></a>
									</li>	
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/12.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/13.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/14.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/15.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/16.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/17.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/18.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>														
								</ul>
					   </div>
					    <div class="section" id="section2">
								<ul>
								    <li class="cutomerli" style="opacity: 1;">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/19.jpg" style=""/>
										<a><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/20.jpg" "/>
										<a ><p>案例详情</p></a>
									</li>	
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/21.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/22.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/23.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/24.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/25.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/26.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/27.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>														
								</ul>
					   </div>
			      </div>
			</div>


第二个轮播图
<div id="container1" style="width: 1000px;height: 635px; overflow: hidden; margin: 0 auto; margin-bottom: 20px; border: solid 1px #red;">
		         <div class="sections">
			           <div class="section" id="section0">
								<ul>
								    <li class="cutomerli" style="opacity: 1;">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/9.jpg" style=""/>
										<a href="about-detail.jsp" style="color:red"><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/1.jpg" "/>
										<a ><p>案例详情</p></a>
									</li>	
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/2.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/3.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/4.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/5.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/6.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/7.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/8.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>														
								</ul>
					   </div>
					    <div class="section" id="section1">
								<ul>
								    <li class="cutomerli" style="opacity: 1;">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/10.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/11.jpg" "/>
										<a ><p>案例详情</p></a>
									</li>	
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/12.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/13.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/14.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/15.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/16.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/17.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/18.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>														
								</ul>
					   </div>
					    <div class="section" id="section2">
								<ul>
								    <li class="cutomerli" style="opacity: 1;">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/19.jpg" style=""/>
										<a><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/20.jpg" "/>
										<a ><p>案例详情</p></a>
									</li>	
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/21.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/22.jpg" "/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/23.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/24.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/25.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/26.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>
									<li class="cutomerli">
										<img src="${pageContext.request.contextPath}/Kingsware/webpage/customer/zq/27.jpg" style=""/>
										<a ><p>案例详情</p></a>							
									</li>														
								</ul>
					   </div>
			      </div>

js代码
$("#container").PageSwitch({
		direction:'horizontal',
		easing:'ease-in',
		duration:1000,
		autoPlay:true,
		loop:'false'
	}); 
	
	$("#container1").PageSwitch({
		direction:'horizontal',
		easing:'ease-in',
		duration:1000,
		autoPlay:true,
		loop:'false'
	}); 

只有第一个轮播图生效

**Comment by ParadeTo** [comment]
配置下这个，两个的类名不要一样，要不就混在一起了，样式自己再调一调：

```
selectors : {
	sections : ".sections",  // 容器
	section : ".section", // 每一页
	pages : ".pages", // 分页导航(小圆点)
	active : ".active" // 当前激活页
},
```

**Comment by leimingming1996** [comment]
问题解决了 ，感谢
